version: "3.8"

services:
  emotion-ai:
    image: tp9ns/recruitai:emotion-ai
    container_name: emotion-ai
    ports:
      - "8000:8000"
    networks:
      - backend-net   # backend와 통일
      
  interview-ai:
    image: tp9ns/recruitai:interview-ai
    container_name: interview-ai
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - backend-net

  tracking-ai:
    image: tp9ns/recruitai:tracking-ai
    container_name: tracking-ai
    ports:
      - "8003:8003"
    networks:
      - backend-net
      
networks:
  backend-net:
    external: true
    name: recruitai_backend-net  # 이미 존재하는 네트워크에 붙는다는 의미