[project]
name = "interview"
version = "0.1.0"
description = ""
authors = [
    {name = "seongmin",email = "sungmin2959@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "accelerate (==1.9.0)",
    "aiohappyeyeballs (==2.6.1)",
    "aiohttp (==3.12.14)",
    "aiosignal (==1.4.0)",
    "annotated-types (==0.7.0)",
    "anyio (==4.9.0)",
    "attrs (==25.3.0)",
    "bitsandbytes (==0.46.1)",
    "cachetools (==5.5.2)",
    "certifi (==2025.7.14)",
    "charset-normalizer (==3.4.2)",
    "click (==8.2.1)",
    "colorama (==0.4.6)",
    "dataclasses-json (==0.6.7)",
    "datasets (==4.0.0)",
    "dill (==0.3.8)",
    "distro (==1.9.0)",
    "fastapi (==0.116.1)",
    "ffmpeg-python (==0.2.0)",
    "filelock (==3.18.0)",
    "filetype (==1.2.0)",
    "frozenlist (==1.7.0)",
    "fsspec (==2025.3.0)",
    "future (==1.0.0)",
    "google-ai-generativelanguage (==0.6.15)",
    "google-api-core (==2.25.1)",
    "google-api-python-client (==2.177.0)",
    "google-auth (==2.40.3)",
    "google-auth-httplib2 (==0.2.0)",
    "google-generativeai (==0.8.5)",
    "googleapis-common-protos (==1.70.0)",
    "greenlet (==3.2.3)",
    "grpcio (==1.74.0)",
    "grpcio-status (==1.71.2)",
    "h11 (==0.16.0)",
    "httpcore (==1.0.9)",
    "httplib2 (==0.22.0)",
    "httptools (==0.6.4)",
    "httpx (==0.28.1)",
    "httpx-sse (==0.4.1)",
    "huggingface-hub (==0.34.2)",
    "idna (==3.10)",
    "jinja2 (==3.1.6)",
    "jiter (==0.10.0)",
    "jsonpatch (==1.33)",
    "jsonpointer (==3.0.0)",
    "langchain (==0.3.27)",
    "langchain-community (==0.3.27)",
    "langchain-core (==0.3.72)",
    "langchain-google-genai (==2.0.10)",
    "langchain-openai (==0.3.28)",
    "langchain-text-splitters (==0.3.9)",
    "langgraph (==0.6.1)",
    "langgraph-checkpoint (==2.1.1)",
    "langgraph-prebuilt (==0.6.1)",
    "langgraph-sdk (==0.2.0)",
    "langsmith (==0.4.8)",
    "llvmlite (==0.44.0)",
    "markupsafe (==3.0.2)",
    "marshmallow (==3.26.1)",
    "more-itertools (==10.7.0)",
    "mpmath (==1.3.0)",
    "multidict (==6.6.3)",
    "multiprocess (==0.70.16)",
    "mypy-extensions (==1.1.0)",
    "networkx (==3.5)",
    "numba (==0.61.2)",
    "numpy (==2.2.6)",
    "openai (==1.97.1)",
    "openai-whisper (==20250625)",
    "orjson (==3.11.1)",
    "ormsgpack (==1.10.0)",
    "packaging (==25.0)",
    "pandas (==2.3.1)",
    "peft (==0.16.0)",
    "propcache (==0.3.2)",
    "proto-plus (==1.26.1)",
    "protobuf (==5.29.5)",
    "psutil (==7.0.0)",
    "pyarrow (==21.0.0)",
    "pyasn1 (==0.6.1)",
    "pyasn1-modules (==0.4.2)",
    "pydantic (==2.11.7)",
    "pydantic-settings (==2.10.1)",
    "pydantic-core (==2.33.2)",
    "pyparsing (==3.2.3)",
    "python-dateutil (==2.9.0.post0)",
    "python-dotenv (==1.1.1)",
    "python-multipart (==0.0.20)",
    "pytz (==2025.2)",
    "pyyaml (==6.0.2)",
    "regex (==2024.11.6)",
    "requests (==2.32.4)",
    "requests-toolbelt (==1.0.0)",
    "rsa (==4.9.1)",
    "safetensors (==0.5.3)",
    "setuptools (==78.1.1)",
    "six (==1.17.0)",
    "sniffio (==1.3.1)",
    "sqlalchemy (==2.0.42)",
    "starlette (==0.47.2)",
    "sympy (==1.14.0)",
    "tenacity (==9.1.2)",
    "tiktoken (==0.9.0)",
    "tokenizers (==0.21.4)",
    "torch (==2.7.1)",
    "tqdm (==4.67.1)",
    "transformers (==4.54.0)",
    "trl (==0.19.1)",
    "typing-inspect (==0.9.0)",
    "typing-inspection (==0.4.1)",
    "typing-extensions (==4.14.1)",
    "tzdata (==2025.2)",
    "uritemplate (==4.2.0)",
    "urllib3 (==2.5.0)",
    "uvicorn (==0.35.0)",
    "watchfiles (==1.1.0)",
    "websockets (==15.0.1)",
    "wheel (==0.45.1)",
    "xxhash (==3.5.0)",
    "yarl (==1.20.1)",
    "zstandard (==0.23.0)",
    "chromadb (>=1.0.15,<2.0.0)",
    "firebase-admin (>=7.1.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
